SET IDENTITY_INSERT [dbo].[Products] ON
INSERT INTO [dbo].[Products] ([Id], [name], [length], [width], [height], [cost], [weight], [mominal_number], [unit_of_measurment]) VALUES (1, N'Moloko', 427, 835, 849, 11, 33, 3, N'кг')
INSERT INTO [dbo].[Products] ([Id], [name], [length], [width], [height], [cost], [weight], [mominal_number], [unit_of_measurment]) VALUES (2, N'Car', 911, 726, 477, 48, 19, 7, N'кг')
INSERT INTO [dbo].[Products] ([Id], [name], [length], [width], [height], [cost], [weight], [mominal_number], [unit_of_measurment]) VALUES (3, N'Prod', 20, 382, 720, 57, 24, 18, N'кг')
INSERT INTO [dbo].[Products] ([Id], [name], [length], [width], [height], [cost], [weight], [mominal_number], [unit_of_measurment]) VALUES (4, N'Moto', 783, 300, 300, 300, 300, 300, N'кг')
INSERT INTO [dbo].[Products] ([Id], [name], [length], [width], [height], [cost], [weight], [mominal_number], [unit_of_measurment]) VALUES (5, N'ProductX', 537, 366, 671, 48, 19, 21, N'кг')
INSERT INTO [dbo].[Products] ([Id], [name], [length], [width], [height], [cost], [weight], [mominal_number], [unit_of_measurment]) VALUES (6, N'ProductX', 64, 735, 114, 16, 28, 10, N'кг')
INSERT INTO [dbo].[Products] ([Id], [name], [length], [width], [height], [cost], [weight], [mominal_number], [unit_of_measurment]) VALUES (7, N'ProductX', 632, 275, 51, 47, 17, 22, N'кг')
INSERT INTO [dbo].[Products] ([Id], [name], [length], [width], [height], [cost], [weight], [mominal_number], [unit_of_measurment]) VALUES (8, N'ProductX', 222, 778, 917, 16, 37, 1, N'кг')
INSERT INTO [dbo].[Products] ([Id], [name], [length], [width], [height], [cost], [weight], [mominal_number], [unit_of_measurment]) VALUES (9, N'ProductX', 693, 547, 162, 25, 37, 11, N'кг')
INSERT INTO [dbo].[Products] ([Id], [name], [length], [width], [height], [cost], [weight], [mominal_number], [unit_of_measurment]) VALUES (10, N'ProductX', 864, 88, 298, 30, 31, 15, N'кг')
INSERT INTO [dbo].[Products] ([Id], [name], [length], [width], [height], [cost], [weight], [mominal_number], [unit_of_measurment]) VALUES (11, N'ProductX', 171, 806, 540, 79, 36, 2, N'кг')
INSERT INTO [dbo].[Products] ([Id], [name], [length], [width], [height], [cost], [weight], [mominal_number], [unit_of_measurment]) VALUES (12, N'ProductX', 266, 543, 358, 35, 20, 20, N'кг')
INSERT INTO [dbo].[Products] ([Id], [name], [length], [width], [height], [cost], [weight], [mominal_number], [unit_of_measurment]) VALUES (13, N'ProductX', 223, 134, 601, 72, 11, 1, N'кг')
INSERT INTO [dbo].[Products] ([Id], [name], [length], [width], [height], [cost], [weight], [mominal_number], [unit_of_measurment]) VALUES (14, N'Название', 1, 1, 1, 1, 1, 1, N'1')
INSERT INTO [dbo].[Products] ([Id], [name], [length], [width], [height], [cost], [weight], [mominal_number], [unit_of_measurment]) VALUES (15, N'Название', 1, 1, 1, 1, 1, 1, N'1')
INSERT INTO [dbo].[Products] ([Id], [name], [length], [width], [height], [cost], [weight], [mominal_number], [unit_of_measurment]) VALUES (16, N'Название', 2, 2, 2, 2, 2, 2, N'2')
INSERT INTO [dbo].[Products] ([Id], [name], [length], [width], [height], [cost], [weight], [mominal_number], [unit_of_measurment]) VALUES (17, N'Название', 10, 12, 12, 12, 12, 100, N'kg')
SET IDENTITY_INSERT [dbo].[Products] OFF
